# Challenge: Promotions

In this challenge, you'll develop codes to parse and analyze data returned from another API on Zalando such as [Promos homme (Men's Promotions)
](https://www.zalando.fr/promo-homme/) or [Promos femme (Women's Promotions)](https://www.zalando.fr/promo-femme/). The workflow is almost the same as in the guided lesson but you'll work with different data.

## Obtaining the link

Wrote your codes in the cell below to obtain the data from the API endpoint you choose. A recap of the workflow:

1. Examine the webpages and choose one that you want to work with.

1. Use Google Chrome's DevTools to inspect the XHR network requests. Find out the API endpoint that serves data to the webpage.

1. Test the API endpoint in the browser to verify its data.

1. Change the page number offset of the API URL to test if it's working.

In [4]:
# your code here
# Paste the url you obtained for your data
url='https://www.zalando.fr/api/catalog/articles?categories=promo-femme&limit=84&offset=84&sort=popularity'
headers = {'User-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36'}

## Reading the data

In the next cell, use Python to obtain data from the API endpoint you chose in the previous step. Workflow:

1. Import libraries.

1. Define the initial API endpoint URL.

1. Make request to obtain data of the 1st page. Flatten the data and store it in an empty object variable.

1. Find out the total page count in the 1st page data.

1. Use a FOR loop to make requests for the additional pages from 2 to page count. Append the data of each additional page to the flatterned data object.

1. Print and review the data you obtained.

In [10]:
# your code here
import re
import json
import requests
import pandas as pd
from pandas.io.json import json_normalize
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [11]:
response = requests.get(url, headers =headers)
results = response.json()
flatten_data = json_normalize(results)
flatten_data_1 = json_normalize(flatten_data.articles[0])
#flatten_data_1
#results #page_count': 892

In [13]:
lst = []
for i in range(20):#20 para que no pete
    count = 84*i
    urls = 'https://www.zalando.fr/api/catalog/articles?categories=promo-enfant&limit=84&offset='+str(count)+'&sort=sale'
    response_all = requests.get(urls, headers =headers)
    results_all = response_all.json()
    flatten_data_all = json_normalize(results_all)
    flatten_data_all = json_normalize(flatten_data_all.articles[0])
    lst.append(flatten_data_all)
data = pd.concat(lst)

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:10: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  # Remove the CWD from sys.path while we load stuff.

In [14]:
data

,amount,brand_name,delivery_promises,family_articles,flags,is_premium,media,name,price.has_different_original_prices,price.has_different_prices,...,price.has_discount_on_selected_sizes_only,price.original,price.promotional,product_group,sizes,sku,tracking_information.impression_beacon,tracking_information.metrigo_impression_urls,tracking_information.source,url_key
0,NaN,Nike Sportswear,[],"[{'sku': 'NI116D04L-Q11', 'url_key': 'nike-spo...","[{'key': 'discountRate', 'value': 'Jusqu’à -20...",False,[{'path': 'NI/11/6D/04/LQ/11/NI116D04L-Q11@8.j...,COURT BOROUGH MID BOOT WINTERIZED - Chaussures...,False,True,...,False,"54,95 €","43,95 €",shoe,"[28, 28.5, 29.5, 30, 31.5, 32, 33.5, 34, 35]",NI116D04L-Q11,https://ccp-et.metrigo.zalan.do/event/sbv?z=dd...,[https://ccp-et.metrigo.zalan.do/event/sbv?z=d...,ccp,nike-sportswear-court-borough-mid-boot-winteri...
1,NaN,Nike Sportswear,[],"[{'sku': 'NI114D0B9-Q14', 'url_key': 'nike-spo...","[{'key': 'discountRate', 'value': '-20%', 'tra...",False,[{'path': 'NI/11/4D/0B/9Q/14/NI114D0B9-Q14@9.j...,AIR MAX 200 - Baskets basses - black/metallic ...,False,False,...,False,"104,95 €","83,95 €",shoe,"[35.5, 36.5, 37.5, 38, 38.5, 40]",NI114D0B9-Q14,https://ccp-et.metrigo.zalan.do/event/sbv?z=dd...,[https://ccp-et.metrigo.zalan.do/event/sbv?z=d...,ccp,nike-sportswear-air-max-200-baskets-basses-ni1...
2,NaN,Nike Sportswear,[],"[{'sku': 'NI114D0C8-Q11', 'url_key': 'nike-spo...","[{'key': 'discountRate', 'value': 'Jusqu’à -20...",False,[{'path': 'NI/11/4D/0C/8Q/11/NI114D0C8-Q11@8.j...,SHOX R4 BG - Baskets basses - enigma,False,True,...,False,"114,95 €","91,95 €",shoe,"[35.5, 36, 36.5, 37.5, 38, 38.5, 39, 40]",NI114D0C8-Q11,https://ccp-et.metrigo.zalan.do/event/sbv?z=dd...,[https://ccp-et.metrigo.zalan.do/event/sbv?z=d...,ccp,nike-sportswear-shox-r4-bg-baskets-basses-enig...
3,NaN,adidas Originals,[],"[{'sku': 'AD116D007-A11', 'url_key': 'adidas-o...","[{'key': 'discountRate', 'value': 'Jusqu’à -30...",False,[{'path': 'AD/11/6D/00/7A/11/AD116D007-A11@12....,STAN SMITH - Baskets basses - white,False,True,...,False,"54,95 €","38,45 €",shoe,"[28, 29, 30, 31, 32, 33, 34, 35, 28 1/2, 30 1/...",AD116D007-A11,NaN,NaN,NaN,adidas-originals-stan-smith-baskets-basses-bla...
4,NaN,adidas Originals,[],"[{'sku': 'AD126L00J-Q11', 'url_key': 'adidas-o...","[{'key': 'discountRate', 'value': 'Jusqu’à -35...",False,[{'path': 'AD/12/6L/00/JQ/11/AD126L00J-Q11@8.j...,JACKET - Veste d'hiver - black/white,False,True,...,False,"64,95 €","41,95 €",clothing,"[3-4a, 4-5a, 5-6a, 6-7a, 7-8a]",AD126L00J-Q11,NaN,NaN,NaN,adidas-originals-jacket-veste-dhiver-blackwhit...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,NaN,Hype,[],"[{'sku': 'HY553I008-T11', 'url_key': 'hype-bac...","[{'key': 'discountRate', 'value': '-25%', 'tra...",False,[{'path': 'HY/55/3I/00/8T/11/HY553I008-T11@3.j...,BACKPACK DINO SPACE - Sac à dos - multi,False,False,...,False,"29,95 €","22,45 €",accessoires,[One Size],HY553I008-T11,NaN,NaN,NaN,hype-backpack-dino-space-sac-a-dos-multi-hy553...
80,NaN,Lemon Beret,[],"[{'sku': 'LEG23K01G-K12', 'url_key': 'lemon-be...","[{'key': 'discountRate', 'value': '-20%', 'tra...",False,[{'path': 'LE/G2/3K/01/GK/12/LEG23K01G-K12@6.j...,TEEN GIRLS - Sweat à capuche - sky blue,False,False,...,False,"29,95 €","23,95 €",clothing,"[10a, 12a, 14a, 16a]",LEG23K01G-K12,NaN,NaN,NaN,lemon-beret-teen-girls-sweatshirt-sky-blue-leg...
81,NaN,Nike Performance,[],"[{'sku': 'N1243A0YV-Q11', 'url_key': 'nike-per...","[{'key': 'discountRate', 'value': 'Jusqu’à -20...",False,[{'path': 'N1/24/3A/0Y/VQ/11/N1243A0YV-Q11@8.j...,MERCURIAL 7 ACADEMY IC - Chaussures de foot en...,False,True,...,False,"69,95 €","55,95 €",shoe,"[32, 34, 35, 35.5, 36, 36.5, 37.5, 38, 38.5]",N1243A0YV-Q11,NaN,NaN,NaN,nike-performance-7-academy-ic-chaussures-de-fo...
82,NaN,Blue Seven,[],"[{'sku': 'BL823L01R-Q11', 'url_key': 'blue-sev...","[{'key': 'discountRate', 'value': '-60%', 'tra...",False,[{'path': 'BL/82/3L/01/RQ/11/BL823L01R-Q11@8.j...,STEHKRAGEN - Veste d'hiver - schwarz,False,False,...,False,"59,95 €","23,95 €",clothing,"[10a, 12a, 14a, 16a]",BL823L01R-Q11,NaN,NaN,NaN,blue-seven-stehkragen-doudoune-schwarz-bl823l0...
83,NaN,Esprit,[],"[{'sku': 'ES124L042-K11', 'url_key': 'esprit-o...","[{'key': 'discountRate', 'value': 'Jusqu’à -40...",False,[{'path': 'ES/12/4L/04/2K/11/ES124L042-K11@7.j...,OUTDOOR JACKET BABY - Veste d'hiver - bright blue,False,True,...,False,"46,99 €","28,19 €",clothing,"[2a, 6m, 9m, 12m, 18m]",ES124L042-K11,NaN,NaN,NaN,esprit-outdoor-jacket-baby-veste-dhiver-bright...

## Bonus

Extract the following information from the data:

* The trending brand.

* The product(s) with the highest discount.

* The sum of discounts of all goods (sum_discounted_prices divided by sum_original_prices).

In [17]:
# your code here
#trending brand (de 20 paginas) Nike Sportswear: 106
data['brand_name'].value_counts()

Nike Sportswear     106
Nike Performance    103
Lemon Beret          72
Name it              71
Esprit               63
                   ...
Carrement Beau        1
Noé & Zoë             1
clic!                 1
Mainio                1
Birkenstock           1
Name: brand_name, Length: 170, dtype: int64

In [16]:
def string_to_float(df,cl):
    '''
     **import re**
    - extracts numbers with a comma in between from a string
    - list comprehension that iterates through the column and turns the comma into a dot
    - turn the column into a float
    
    input: df[cl] type == str
    output: df[cl] type == float
    
    '''
    df[cl] = df[cl].str.extract('(\d*,\d*)')
    df[cl] = [i.replace(',', '.') for i in df[cl]]
    df[cl] = df[cl].astype(float)
    return df[cl]

In [18]:
data.columns

Index(['amount', 'brand_name', 'delivery_promises', 'family_articles', 'flags',
       'is_premium', 'media', 'name', 'price.has_different_original_prices',
       'price.has_different_prices', 'price.has_different_promotional_prices',
       'price.has_discount_on_selected_sizes_only', 'price.original',
       'price.promotional', 'product_group', 'sizes', 'sku',
       'tracking_information.impression_beacon',
       'tracking_information.metrigo_impression_urls',
       'tracking_information.source', 'url_key'],
      dtype='object')

In [19]:
string_to_float(data, 'price.original')

0      54.95
1     104.95
2     114.95
3      54.95
4      64.95
       ...
79     29.95
80     29.95
81     69.95
82     59.95
83     46.99
Name: price.original, Length: 1680, dtype: float64

In [20]:
string_to_float(data, 'price.promotional')

0     43.95
1     83.95
2     91.95
3     38.45
4     41.95
      ...
79    22.45
80    23.95
81    55.95
82    23.95
83    28.19
Name: price.promotional, Length: 1680, dtype: float64

In [21]:
data['discount'] = data['price.original'] - data['price.promotional']

In [24]:
item = data.groupby('name', as_index = False)['discount'].sum()
item.sort_values(by = 'discount', ascending=False)

                                                   name  discount
709    LIGHT HOOD BOMBER GIRLS - Veste d'hiver - silver    108.00
1547   YOOT PAC - Bottes de neige - wild iris/dark plum     85.50
1111         SHERIN GIRLS PUFF  - Veste d'hiver - black     80.00
1480                          Veste d'hiver - dark blue     79.97
589         JETTY  - Veste de snowboard - medieval blue     78.00
...                                                 ...       ...
1416  TODDLER BOY CITY - T-shirt imprimé - light hea...      1.50
347                 CREW NECK JUMPER - Pullover - black      1.36
1339  TEE REGULAR BURBANK BABY - T-shirt à manches l...      1.30
1050  REVOLUTION 5 - Chaussures de running neutres -...      0.80
807          NEW SKOOL BACKPACK BOYS - Sac à dos - blue      0.80

[1573 rows x 2 columns]